//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<degree_data> degree_data { get; set; }
        public virtual DbSet<degree_type> degree_type { get; set; }
        public virtual DbSet<field_of_study> field_of_study { get; set; }
        public virtual DbSet<language> languages { get; set; }
        public virtual DbSet<study_areas> study_areas { get; set; }
        public virtual DbSet<sub_degree_type> sub_degree_type { get; set; }
        public virtual DbSet<subject_group> subject_group { get; set; }
        public virtual DbSet<university_name> university_name { get; set; }
    }
}
