//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public int languages_pk { get; set; }
        public string languages_name { get; set; }
        public string createdAt { get; set; }
        public string createdBy { get; set; }
        public string modifiedAt { get; set; }
        public string modifiedBy { get; set; }
    }
}
