//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class university_name
    {
        public int uni_pk { get; set; }
        public string uni_name { get; set; }
        public Nullable<int> country_pk { get; set; }
        public string completed { get; set; }
        public Nullable<int> ranking { get; set; }
        public string admission_open { get; set; }
        public string admission_link { get; set; }
        public string createdAt { get; set; }
        public string createdBy { get; set; }
        public string modifiedAt { get; set; }
        public string modifiedBy { get; set; }
    }
}
